// Generated by `wit-bindgen` 0.48.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_ADDER_H
#define __CPP_GUEST_BINDINGS_ADDER_H
#include <cstdint>
#include <utility>
// export_interface Interface(Id { idx: 0 })
namespace exports {
  namespace docs {
    namespace adder {
      namespace add {
        uint32_t Add(uint32_t x, uint32_t y);
      }
    }
  }
}

#endif
