// Generated by `wit-bindgen` 0.48.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_adder(void);
__attribute__((used))
void __component_type_object_force_link_adder_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_adder();
}
#endif
#include "adder_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("docs:adder/add@0.1.0#add")))
int32_t docsX3AadderX2FaddX400X2E1X2E0X23add(int32_t arg0, int32_t arg1)
{
  auto result0 = exports::docs::adder::add::Add((uint32_t(arg0)), (uint32_t(arg1)));
  return (int32_t(result0));
}

// Component Adapters
